# Generated by Django 4.1.3 on 2022-11-24 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 7, 5, 28, 653551, tzinfo=datetime.timezone.utc)),
        ),
    ]
