# Generated by Django 4.1.3 on 2022-12-06 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 3, 40, 23, 529471, tzinfo=datetime.timezone.utc)),
        ),
    ]
