# Generated by Django 4.1.3 on 2022-12-07 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 3, 55, 41, 333671, tzinfo=datetime.timezone.utc)),
        ),
    ]
