# Generated by Django 4.1.3 on 2022-12-15 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_publicationshortdate_alter_post_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 5, 7, 44, 503279, tzinfo=datetime.timezone.utc)),
        ),
    ]
