# Generated by Django 4.1.3 on 2022-12-15 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 6, 3, 43, 497753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicationShortDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
