# Generated by Django 4.1.3 on 2022-12-21 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 6, 4, 44, 582201, tzinfo=datetime.timezone.utc)),
        ),
    ]
