# Generated by Django 4.1.3 on 2023-01-05 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='authoravatars'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 5, 32, 55, 117868, tzinfo=datetime.timezone.utc)),
        ),
    ]
