# Generated by Django 4.1.3 on 2023-01-05 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_authoravatar_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 5, 43, 54, 917132, tzinfo=datetime.timezone.utc)),
        ),
    ]
