# Generated by Django 4.1.3 on 2023-01-07 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 10, 57, 16, 781890, tzinfo=datetime.timezone.utc)),
        ),
    ]
