# Generated by Django 4.1.3 on 2023-01-07 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_post_authoravatar_post_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 11, 20, 56, 385960, tzinfo=datetime.timezone.utc)),
        ),
    ]
