# Generated by Django 4.1.3 on 2023-01-08 05:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 5, 0, 9, 214608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='likedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                ('userGiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsIliked', to=settings.AUTH_USER_MODEL)),
                ('userReceiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poststheyliked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
