# Generated by Django 4.1.3 on 2023-01-09 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_post_creationdate_likedposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedposts',
            old_name='userReceiving',
            new_name='userLiked',
        ),
        migrations.RenameField(
            model_name='likedposts',
            old_name='userGiving',
            new_name='userLiking',
        ),
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 4, 6, 8, 64014, tzinfo=datetime.timezone.utc)),
        ),
    ]
