# Generated by Django 4.1.3 on 2023-01-12 04:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0028_alter_likedposts_userliking_alter_post_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 4, 26, 19, 304827, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='savedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='posts.post')),
                ('userSaving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsSaved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'userSaving')},
            },
        ),
    ]
