# Generated by Django 4.1.3 on 2023-01-12 04:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0029_alter_post_creationdate_savedposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likedPosts',
            new_name='likedPost',
        ),
        migrations.RenameModel(
            old_name='savedPosts',
            new_name='savedPost',
        ),
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 4, 27, 15, 814489, tzinfo=datetime.timezone.utc)),
        ),
    ]
