# Generated by Django 4.1.3 on 2023-01-17 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 6, 30, 42, 385401, tzinfo=datetime.timezone.utc)),
        ),
    ]
