# Generated by Django 4.1.2 on 2023-02-09 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 6, 9, 40, 593138, tzinfo=datetime.timezone.utc)),
        ),
    ]
