# Generated by Django 4.1.2 on 2023-03-07 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 3, 12, 23, 774517, tzinfo=datetime.timezone.utc)),
        ),
    ]
