# Generated by Django 4.1.2 on 2023-03-09 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_alter_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 3, 32, 23, 351542, tzinfo=datetime.timezone.utc)),
        ),
    ]
